``` plantuml
@startuml diagrama de actividad  acceso a landing page
'!include  ./skin/blue.plantuml
!include https://raw.githubusercontent.com/vonbeitthia/NodeUml/main/uml/skin/blue.plantuml
|A10usuarioAnonimo|
start
|A53ControladorUsuarios|
if (! usuario) then (usuarioAnonimo)
    :crearUsuarioNoRegistrado;
    detach
endif
if (! rutas) then (rutasPermitidas)
    :crearRutas;
    note left
        rutas permitidas
        rutas bloqueadas
        y rutas no encontradas
    end note
endif
|A51ControladorRutas|
if ( urlRequerida in rutasPermitidas) then
    :servirPagina;
    stop
elseif ( urlRequerida in rutasBloqueadas) then
    |A54ControladorErrores| 
    :servirAccesoNoAutorizado;
    stop
else (rutaInvalida)
    |A54ControladorErrores| 
    :servirPaginaNoEncontrada;
    note right
        para rutas no encontradas
    end note
    stop
endif
@enduml
```