``` plantuml
@startuml analisis de clases
'!include  ./skin/blue.plantuml
!include https://raw.githubusercontent.com/vonbeitthia/NodeUml/main/uml/skin/blue.plantuml
allowmixing
package "Configuraciones" #LightBlue  {
 class env <<entorno>> {
     puertoHttp : int
     archivoLog : "/log/system.log"
 } 
 file "./config/entorno.json" as file1 {
 } 
env ..> file1 : depende de
} 
note right
    configuracion de entorno
 end note
 
 package "Historial" {
     file "./log/system.log"{}
      
 } 
@enduml
```