``` plantuml
@startuml analisis de clases
'!include  ./skin/blue.plantuml
!include https://raw.githubusercontent.com/vonbeitthia/NodeUml/main/uml/skin/blue.plantuml
allowmixing
package "Configuraciones" #LightBlue  {
 class env <<entorno>> {
     puertoHttp : int
     archivoLog : "/log/system.log"
 } 
 file "./config/config.json" as file1 {
 } 
env ..> file1 : depende de
} 
note right
    configuracion de entorno
end note

 package "Historial" {
     file "./log/system.log" as file2 {

     }
     class usuarioLog{
         idUsuario : int
         evento : str
         fechaHora : date
     } 
     usuarioLog .> file2 : incluye
 } 

 note right of Historial
    Registro de eventos
 end note
@enduml
```